version: "3.9"

services:

  load_balancer:
    image: vitorchassot/rinha-2026:latest
    container_name: rinha-lb


    command: ["/app/load_balancer"]

    depends_on:
      - api1
      - api2

    ports:
      - "9999:9999"

    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "7MB"


  api1:
    image: vitorchassot/rinha-2026:latest
    container_name: rinha-api1


    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "172MB"


  api2:
    image: vitorchassot/rinha-2026:latest
    container_name: rinha-api2


    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "171MB"

