version: "3.9"

services:

  load_balancer:
    image: vitorchassot/rinha-2026:v2
    pull_policy: always
    container_name: rinha-lb


    command: ["/app/load_balancer"]

    depends_on:
      - api1
      - api2

    ports:
      - "9999:9999"

    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535


  api1:
    image: vitorchassot/rinha-2026:v2
    pull_policy: always
    container_name: rinha-api1


    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api2:
    image: vitorchassot/rinha-2026:v2
    pull_policy: always
    container_name: rinha-api2


    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "165MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
